spring:
  question:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/tinkinator
      username: tinkinator-superuser
      password: tinkinator
      driver-class-name: org.postgresql.Driver
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 900000
  other:
    datasource:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 900000
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationSorter: method
  api-docs:
    path: /api-docs